# Generated by Django 5.2.5 on 2025-09-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(db_column='booking_id', primary_key=True, serialize=False)),
                ('applicant_id', models.IntegerField(db_column='applicant_id')),
                ('org_id', models.IntegerField(db_column='org_id')),
                ('event_type_id', models.IntegerField(db_column='event_type_id')),
                ('venue_id', models.IntegerField(db_column='venue_id')),
                ('event_date', models.DateField(db_column='event_date')),
                ('start_time', models.TimeField(db_column='start_time')),
                ('end_time', models.TimeField(db_column='end_time')),
                ('total_hours', models.DecimalField(db_column='total_hours', decimal_places=2, max_digits=4)),
                ('event_details', models.TextField(db_column='event_details')),
                ('invitation_path', models.CharField(blank=True, db_column='invitation_path', max_length=255)),
                ('pre_arrangement_date', models.DateField(blank=True, db_column='pre_arrangement_date', null=True)),
                ('pre_arrangement_start', models.TimeField(blank=True, db_column='pre_arrangement_start', null=True)),
                ('pre_arrangement_end', models.TimeField(blank=True, db_column='pre_arrangement_end', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_column='status', default='pending', max_length=20)),
                ('permission_granted', models.BooleanField(db_column='permission_granted', default=False)),
                ('granted_by', models.CharField(blank=True, db_column='granted_by', max_length=100)),
                ('grant_date', models.DateField(blank=True, db_column='grant_date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
            ],
            options={
                'db_table': 'bookings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('venue_id', models.AutoField(db_column='venue_id', primary_key=True, serialize=False)),
                ('venue_name', models.CharField(db_column='venue_name', max_length=100)),
                ('capacity', models.IntegerField(db_column='capacity')),
                ('base_rate_2h', models.DecimalField(db_column='base_rate_2h', decimal_places=2, max_digits=10)),
                ('base_rate_4h', models.DecimalField(db_column='base_rate_4h', decimal_places=2, max_digits=10)),
                ('base_rate_6h', models.DecimalField(db_column='base_rate_6h', decimal_places=2, max_digits=10)),
                ('base_rate_6h_plus', models.DecimalField(db_column='base_rate_6h_plus', decimal_places=2, max_digits=10)),
                ('description', models.TextField(db_column='description')),
            ],
            options={
                'db_table': 'venues',
                'ordering': ['venue_name'],
            },
        ),
    ]
