# Generated by Django 5.2.5 on 2025-09-21 08:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("booking", "0002_additionalservice_alter_venue_options_and_more"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="additionalservice",
            table="booking_additionalservice",
        ),
        migrations.AlterModelTable(
            name="applicant",
            table="booking_applicant",
        ),
        migrations.AlterModelTable(
            name="booking",
            table="booking_booking",
        ),
        migrations.AlterModelTable(
            name="bookingservice",
            table="booking_bookingservice",
        ),
        migrations.AlterModelTable(
            name="bookingslot",
            table="booking_bookingslot",
        ),
        migrations.AlterModelTable(
            name="prearrangement",
            table="booking_prearrangement",
        ),
        migrations.AlterModelTable(
            name="pricetier",
            table="booking_pricetier",
        ),
        migrations.AlterModelTable(
            name="venue",
            table="venues",
        ),
        migrations.AlterModelTable(
            name="venueimage",
            table="booking_venueimage",
        ),
    ]
