# Generated by Django 5.2.5 on 2025-09-15 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatbotMessage',
            fields=[
                ('message_id', models.AutoField(db_column='message_id', primary_key=True, serialize=False)),
                ('sender_type', models.CharField(choices=[('user', 'User'), ('admin', 'Admin'), ('system', 'System')], db_column='sender_type', default='user', max_length=20)),
                ('user_id', models.IntegerField(blank=True, db_column='user_id', null=True)),
                ('message_text', models.TextField(db_column='message_text')),
                ('response_text', models.TextField(blank=True, db_column='response_text', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_column='timestamp')),
                ('booking_reference', models.CharField(blank=True, db_column='booking_reference', max_length=100, null=True)),
                ('resolved', models.BooleanField(db_column='resolved', default=False)),
            ],
            options={
                'db_table': 'chatbot_messages',
                'ordering': ['timestamp'],
            },
        ),
    ]
